name: Build and Deploy
on:
  push:
    branches: [ main ]  # ou votre branche de déploiement principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # spécifiez la version de Node.js

    - name: Install dependencies
      run: npm install
      working-directory: Client/identification  # Chemin vers votre répertoire de travail

    - name: Build
      run: npm run build
      working-directory: Client/identification  # Chemin vers votre répertoire de travail

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # la branche où déployer (gh-pages par défaut)
        folder: Client/identification/dist  # le dossier à déployer (dist pour Vite dans votre sous-dossier)